CREATE DATABASE IF NOT EXISTS palestra;
USE palestra;

CREATE TABLE IF NOT EXISTS membri(
id INT AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(100) NOT NULL,
cognome VARCHAR(100) NOT NULL,
email VARCHAR(100),
data_iscrizione DATE NOT NULL
);

DROP TABLE membri;